openclimatefix/nowcasting_datamodel

nowcasting_datamodel/read/read.py, tests/test_read.py
add method to read all locations
added a unittest
=> add method to read all lcations + tests

nowcasting_datamodel/read/read_gsp.py
add logging to gsp yields latest
normal tests
=> add logging

nowcasting_datamodel/read/read_gsp.py, tests/test_read_gsp.py
make regime optional when searching for GSP yield
added a unittest
=> make regime optional, add test

nowcasting_datamodel/fake.py, nowcasting_datamodel/read/read.py, tests/read/test_read.py
add function to read last created_utc time
this be useful for status board
=> add function to read created_utc from database

nowcasting_datamodel/connection.py, nowcasting_datamodel/read/read.py, tests/read/test_read.py
use 'joinedload' to pre load children. This means only one sql command is made. 
Fixes #48 
- unittests
- added a test
=> use joinedload to speed up gett all forecasts objects

nowcasting_datamodel/models/models.py, nowcasting_datamodel/read/read.py, tests/models/test_models.py, tests/read/test_read.py
make sure that target times are sorted
Fixes #
added tests where data is not sorted in the database, this faield before doing the change
=> make sure forecast values are ordered by targettime

README.md, nowcasting_datamodel/fake.py, nowcasting_datamodel/update.py, tests/conftest.py, tests/test_fake.py
make sure `make_fake_forecasts' also makes `forecast_values_latest`
Fixes #
Added test
=> add latest forecasts too to fake forecasts, add test

nowcasting_datamodel/read/read_pv.py, tests/read/test_read_pv.py
This pull request is for issue #127: Make sure pv yield has timezone added to it. Adds timezone to PV yields when calling the `get_pv_yield` function.
Fixes #
Ran unit tests as described in the readme. All tests passed succesfully.
=> add timezone to pv yield

nowcasting_datamodel/read/read.py
This PR adds UTC timezones to the `created_utc` attributes of the returned forecast values, as discussed in [this issue](https://github.com/openclimatefix/nowcasting_datamodel/issues/128). No additional dependencies are required.
Standard unit tests have been run.
Previous similar PR's haven't added any further logic to the unit tests, but would be happy to add some if required.
=> Add timezones to forecast value creation datetimes

nowcasting_datamodel/models/metric.py
In order to get a value for `Daily Latest MAE All GSPs` from the `metric_value` table in the database, the `MetricValue` class in the datamodel needed the `location` field to be updated with `None` instead of `...`. 
This has been updated.
Fixes # => As this is a quick fix, I didn't make an issue for this. 
I ran the Docker tests and they passed.
=> update location field in metric value class

nowcasting_datamodel/read/read_gsp.py, tests/read/test_read_gsp.py
added a function to get the latest gsp capacities from the db. 
This is useful if PVlive goes down, but the we can still use the latest gsp capacites
Helps with https://github.com/openclimatefix/pvnet_app/issues/22
CI Tests + added tests
=> add function to get latest gsp capacities + test

nowcasting_datamodel/save/adjust.py, tests/models/test_convert.py, tests/save/test_adjust.py
Update the adjust mw value to
- be 0 if the forecast value is 0
- restrict to 20% of forecast_value
Added tests
=> add 20% restrict on adjust value

nowcasting_datamodel/models/forecast.py
The way the ForecastValueYearMonth classes are created for each year and month currently causes a warning message when this library is imported like:
```
warnings.warn(message, UserWarning)
.../nowcasting_datamodel/models/forecast.py:212: SAWarning: This declarative base already contains a class 
with the same class name and module name as nowcasting_datamodel.models.forecast.ForecastValueYearMonth, 
and will be replaced in the string-lookup table.
```
This pull request creates the classes dynamically and should remove the warning message since the class names are distinct for each year and month
Closes #148
=> Create ForecastValueYearMonth with factory function to avoid warning message

nowcasting_datamodel/save/update.py, tests/save/test_update.py
Make sure latest forecast also has the input_data_lates_updated as the most recent
Linked with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/337
Added a test
=> update, +. test

nowcasting_datamodel/models/forecast.py, nowcasting_datamodel/models/gsp.py, nowcasting_datamodel/models/metric.py, nowcasting_datamodel/models/models.py, nowcasting_datamodel/models/pv.py
This PR refers to the issue #281 : pydantic: Upgrade validator to field_validator
I followed the instructions in the link provided and the recommendations in the Pydantic migration guide.
This lead to the subsequent modifications : 
- upgraded validator decorators to field_validators decorators
- modified _normalize_target_time like functions that referred to validator function, to normalize_target_time like functions with field_validator decorations to match pydantic V2 recommendations
I tested via the test framework as seen in the readme file. As the modification are minors, it should be enough.
=> Upgrade pydantic validator to field_validator (#281)

nowcasting_datamodel/save/save.py, requirements.txt
Add option to not save to last seven day forecast value tables
Helps with https://github.com/openclimatefix/pvnet_app/issues/93
CI tests
=> ad option to not save to last_seven_days

infrastructure/docker/Dockerfile, nowcasting_datamodel/models/convert.py, nowcasting_datamodel/models/forecast.py, nowcasting_datamodel/national.py, nowcasting_datamodel/save/adjust.py, tests/models/test_models.py, tests/read/test_read.py, tests/read/test_read_gsp.py, tests/read/test_read_models.py, tests/test_fake.py, tests/test_national.py
This PR refers to the issue #284 :  from_orm method is deprecated in pydantic V2
I updated the models and tests that called the deprecated pydantic method from_orm. They now call model_validate as advised in the Pydantic migration guide.
The Forecast and ForecastValue models had methods that overwrote the pydantic from_orm method. I leaved those methods in the models, but they now call model_validate instead of from_orm. I also created model_validate methods for those classes, having the same behavior as calling from_orm. 
I tested via the test framework as seen in the readme file. As the modification are minors, it should be enough.
=> Change Pydantic from_orm to model_validate (#284)

nowcasting_datamodel/read/read_gsp.py
add `datetime_utc` to `get_latest_gsp_capacities`
Helps with https://github.com/openclimatefix/pvnet_app/issues/99
CI tests
=> add datetime_utc into get_latest_gsp_capacities

nowcasting_datamodel/read/read_user.py, tests/read/test_read_user.py
Adds URL filtering capabilities to API request retrieval functions, enabling more granular control over request filtering.
- Added `include_in_url` and `exclude_in_url` optional parameters to API request retrieval functions
- Implemented URL-based filtering using SQLAlchemy's `like()` method
Fixes #298 with ability to filter API requests by URL content.
- Manual testing of new filtering parameters
- Verified compatibility with existing codebase
- Python 3.8+
- SQLAlchemy 1.4.x
- Pytest for unit testing
=> Add URL Filtering Capabilities to API Request Retrieval Functions

nowcasting_datamodel/read/read_gsp.py, tests/read/test_read_gsp.py
Add method to not load gsp capacities if nan. SO we only load non nna gsp gsp capacities
https://github.com/openclimatefix/uk-pvnet-app/issues/172
- CI tests
- extra tests
=> Gsp no nans

nowcasting_datamodel/models/forecast.py, nowcasting_datamodel/read/read.py
This PR improves the clarity of the `target_time` field in the `ForecastValue` model by:
- Updating the `description` to specify that `target_time` refers to the **end of the forecasted period**.
- Adding an example to illustrate how `target_time` should be interpreted (e.g., "a `target_time` of 12:30 refers to the period from 12:00 to 12:30").
These changes aim to make the API easier to understand and reduce potential confusion for developers and users working with forecasted data.
Fixes [openclimatefix](https://github.com/openclimatefix)#177 
- Verified that the updated description does not affect any existing functionality.
- Confirmed that the behavior of the `target_time` field remains unchanged in the model and API.
- Please review the updated description and example for **accuracy …
=> Clarify target_time Description in ForecastValue Model ( issue #177 )

nowcasting_datamodel/fake.py, tests/test_fake.py
add an option to add forecast_creation_time when making a fake forecast
#316
=> add forecast_creation_time option to make fake forecast

nowcasting_datamodel/models/forecast.py, nowcasting_datamodel/save/update.py, tests/save/test_update.py
Fix for init datetime
This will help https://github.com/openclimatefix/uk-pv-national-gsp-api/pull/426
CI tests
=> Fix for forecast latest init time

nowcasting_datamodel/read/read.py
- moved the created filter to 2 days. This helps with loading N hours forecasts in the night, which are made more than 1 day before deliever
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/453
=> change low create_utc_filter to minus 2 days
