openclimatefix/nowcasting_datamodel

- nowcasting_datamodel/national.py
- nowcasting_datamodel/read/read.py
- tests/test_read.py
add read label option to get locations
normal unittests
> Add label read location

- nowcasting_datamodel/read/read.py
- requirements.txt
- tests/test_read.py
Function to update the latest data table
Fixes #21 
add a test
> add function to update latest, + test

- nowcasting_datamodel/read/read_gsp.py
- tests/test_read_gsp.py
add read function for GSPYield
related to https://github.com/openclimatefix/nowcasting_api/issues/77
added a unit test
> add read function for gsp yield + test

- nowcasting_datamodel/read/read_pv.py
option for py sistems in pv yield read
Fixes #
> make pv systems optional in pv yield read

- nowcasting_datamodel/national.py
- tests/conftest.py
- tests/test_national.py
fix for making national forecast
> Fix for national

- nowcasting_datamodel/fake.py
- nowcasting_datamodel/migrations/app.py
- nowcasting_datamodel/models/models.py
- tests/models/test_models.py
Add option to normalize Forecasts
Fixes #
> add normalize function on pydantic models

- nowcasting_datamodel/models/models.py
- tests/models/test_models.py
Tidy up normalized power, so the original power is also there
unittests
> add extra field to pydantic object for normalized power

- nowcasting_datamodel/models/gsp.py
fix for location object
Fixes #
unittests
> make sure installed capacity is transfered

- nowcasting_datamodel/fake.py
- nowcasting_datamodel/read/read.py
- nowcasting_datamodel/update.py
- tests/test_save.py
- tests/test_update.py
Fix for getting historic forecasts id for update
Fixes #
- added to tests
- normal unittests
> Fix update

- nowcasting_datamodel/read/read.py
- tests/read/test_read.py
Make sure 'target_time' filter works properly
https://github.com/openclimatefix/nowcasting_api/issues/113
TDD: changed test first, then fixed code
> Datamodel filter

- nowcasting_datamodel/read/read_pv.py
fix read pv function, so provider can be put in sperately
Fixes #
normal unittests
> split out provider in read function

- archive/locations_2022_07_02.csv
add archive of locations
csv file
This is good to have for July 19th change to pvlive
Fixes #85 
normal CI
> add archive of locations

- nowcasting_datamodel/__init__.py
reduce number of gsps to 314
Fixes #
> chang n gsps to 314

- nowcasting_datamodel/read/read.py
- nowcasting_datamodel/read/read_gsp.py
- nowcasting_datamodel/update.py
- tests/read/test_read.py
- tests/read/test_read_gsp.py
- tests/test_update.py
Speed up
- locations read fot gsp_yield
- locations for updating historic
Fixes #
UI (and printing logs
tested on local api, to check speed
> Speed up update

- nowcasting_datamodel/update.py
fix to make sure gsp 317 is also updated
Fixes #
CI tests
> fix update to include gsp=317

- nowcasting_datamodel/read/read.py
add filter on created time also
Fixes #
normal CI, could add an extra test, but havent
> make sure to filter created_utc to be less than 4 hours from now

- nowcasting_datamodel/connection.py
- nowcasting_datamodel/fake.py
- tests/read/test_read.py
- tests/read/test_read_forecast_horizon.py
- tests/test_databaseconnection.py
- tests/test_fake.py
- tests/test_save.py
- tests/test_update.py
add a method to make a  fake gsp yields
Fixes #
normal CI + new tests
> add fake gsp yield + tests

- nowcasting_datamodel/read/read_gsp.py
- tests/read/test_read_gsp.py
Add read filter to gsp yield latest
Helps with https://github.com/openclimatefix/GSPConsumer/issues/45
CI test + new one
> add optilnal filter on gsp yields

- nowcasting_datamodel/read/read.py
Add end_target_time to 'get_latest_forecast_for_gsps'
Fixes #
Normal CI
> add a end_datetime filter on

- nowcasting_datamodel/fake.py
- tests/test_fake.py
update fake data to be like a solar profile, maximum is between 0.9 and 1, and 0 at nightime
Fixes #122 
normal tests + other tests
> make fake data follow cos^2 profile of the day

- README.md
This PR adds instructions to the README to fix a potential issue for Apple Silicon users caused by a bad build upstream of PG. Not sure if this is this projects preferred way of tracking such suggestions, but thought I'd suggest this PR if helpful.
Tested on my M1 Pro machine.
> Update readme for Apple M1 error

- nowcasting_datamodel/models/convert.py
- nowcasting_datamodel/models/forecast.py
- nowcasting_datamodel/read/read.py
- tests/models/test_convert.py
- tests/read/test_read_forecast_horizon.py
add function to convert `ForecastValueSevenDaysSQL` to `Forecast` objects
Fixes #144 
added a test
> add convert function and tests

- nowcasting_datamodel/models/forecast.py
- tests/models/test_models.py
add limit on adjust method
Fixes #
added tests
> add default limit on adjust method

- nowcasting_datamodel/models/convert.py
- tests/models/test_convert.py
fix convert df to national and save
CI tests + added to test
> Fix convert

- nowcasting_datamodel/read/blend.py
- nowcasting_datamodel/read/read.py
- tests/read/test_blend.py
first version of blending forecast together
Fixes #160 
Ci tests + extras
> first version of blend

- nowcasting_datamodel/models/metric.py
- nowcasting_datamodel/read/blend/blend.py
- nowcasting_datamodel/read/blend/utils.py
- nowcasting_datamodel/read/blend/weights.py
- nowcasting_datamodel/read/read_metric.py
- requirements.txt
add structlogs to blend functions
CI tests, and ran API locally
> add structlogs

- nowcasting_datamodel/read/read.py
- tests/read/test_read.py
add option to load national or not in `get_all_gsp_ids_latest_forecast`
added a test
> add option to load national

- nowcasting_datamodel/save/adjust.py
- tests/save/test_adjust.py
make sure adjust works for more than 8 hours as well
Fixes #
> get adjuster values for more than 8 hours

- nowcasting_datamodel/save/save.py
- tests/save/test_save.py
Make applying the adjuster optional
> make adjuster optional

- nowcasting_datamodel/read/read.py
be able to load model without the version
CI tests, and tested locally
> option to get model without version

- nowcasting_datamodel/read/read.py
> filter by model id in forecast value lates table

- nowcasting_datamodel/fake.py
- nowcasting_datamodel/read/read_metric.py
upgrade read function, this is for PVnet_v2 to use
Use model name from when reading ME metric
> read model_value from modelml.name by

- nowcasting_datamodel/read/read_pv.py
- tests/read/test_read_pv.py
Add distinct option to reading pv data
Ci tests, and ran query locally on db
> add distinct options to pv read

- nowcasting_datamodel/save/save.py
- tests/save/test_save.py
Add override of USE_ADJUSTER to the save method
added a test
> Use adjuster env var

- nowcasting_datamodel/read/read_gsp.py
- tests/read/test_read_gsp.py
Function to read all gsp values and sum them up
Helps with https://github.com/openclimatefix/uk-analysis-dashboard/issues/29
Added a test
> add function to sum up gsp values

- nowcasting_datamodel/fake.py
- nowcasting_datamodel/models/forecast.py
- nowcasting_datamodel/models/gsp.py
- nowcasting_datamodel/models/metric.py
- nowcasting_datamodel/read/read.py
- tests/models/conftest.py
- tests/models/test_gsp.py
- tests/models/test_metric.py
- tests/models/test_models.py
- tests/read/blend/test_blend.py
- tests/read/test_read.py
- tests/read/test_read_forecast_horizon.py
- tests/read/test_read_gsp.py
- tests/save/test_update.py
- tests/test_fake.py
- tests/test_fake_pv.py
- tests/test_utils.py
Fixes #194 
Also includes a few minor additional improvements:
- [Fix flake8 errors in tests, mainly due to unused imports](https://github.com/openclimatefix/nowcasting_datamodel/commit/9db86bc3cdd28aa3a1adba6810023b647073541d)
- [Fix typing errors which were getting caught in linting locally](https://github.com/openclimatefix/nowcasting_datamodel/commit/27a38c24be3aa2cc9c614aede9cae17b28819bf2)
- Fix some typos in comments.
- [Fix BST-dependent tests in test_read.](https://github.com/openclimatefix/nowcasting_datamodel/commit/fc163074584330193c48c4a4ff93eb743f077d40) This one I'm a bit less sure on, but I believe there is a timezone dependant test here which relies on non-BST timing which failed locally until I removed the timezones. See errors below, let me know if there's something I'm …
> Issue/194 Use default value for nil adjust_mw 

- nowcasting_datamodel/read/blend/blend.py
- tests/read/blend/test_blend.py
Horrible fix to do with some pandas indexes
Fixes https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/247
CI test and ran API locally with this change
> TDD: add test

- nowcasting_datamodel/fake.py
Very small fix for fake forefcast values. Tested whn adjusting the API
Tested whn adjusting the API
CI tests here
> add model if into fake forecast value latest

- nowcasting_datamodel/read/read.py
- tests/read/test_read.py
add end datetime filters
Helps with https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/269
- CI tests
- added to tests
> add end datetime filters

- nowcasting_datamodel/save/update.py
- tests/save/test_update.py
Update model version number in historic forecast when saving
CI tests
> update model version when saving to historic forecast

- nowcasting_datamodel/read/read.py
- tests/read/test_read.py
Need for https://github.com/openclimatefix/uk-pv-national-gsp-api/issues/270
Fixes #
CI tests + new test
> and gsp_ids filter to read forecast + tests

- nowcasting_datamodel/models/metric.py
Allow Nonw for time_of_day
Fixes https://github.com/openclimatefix/uk-analysis-dashboard/issues/110
Ran analysis dashbaord locally
> add Optional in metric values

- infrastructure/docker/Dockerfile
Change python docker code to python 3.11
Fixes #
CI tests
> upgrade to python311

- nowcasting_datamodel/save/update.py
change now to on the hour. This should make sql queries more speed up
Fixes #
Ci tests
> change clip now time to on the hour

- nowcasting_datamodel/models/forecast.py
- nowcasting_datamodel/models/gsp.py
- nowcasting_datamodel/models/metric.py
- nowcasting_datamodel/models/models.py
- nowcasting_datamodel/models/pv.py
- nowcasting_datamodel/utils.py
- tests/test_utils.py
Handles conversion of strings to datetime within validators. This is required due to the numpy update. 
Ran tests locally.
> Conversion to datetime

- nowcasting_datamodel/migrations/forecast/versions/06ced43c1321_2025_partitions.py
Migration to attached partition tables to forecast_value
Fixes bug in #304 
- CI tests
- manually sql, confirm bug fix
> add migration to attached partition tables

- nowcasting_datamodel/fake.py
- nowcasting_datamodel/migrations/app.py
- Set fake data t0 to now
- amend truths to be in KW not MW (as capacity is in MW)
- Correct a few typos
Locally and with tests
> Set fake data to now; amend truths to KW

- nowcasting_datamodel/fake.py
Bug introduced in my previous PR on fake data
Locally run with API, test and CI
> Fake data fixes: remove erroneous x1000

- nowcasting_datamodel/read/read.py
Improve logging when forecasts are sorted
Fixes #
> improve logging for sorting

- nowcasting_datamodel/models/forecast.py
Fix for allowing pydantic model to ne None
Ci tests
> make pydantic datetime | None
